"""教务系统子包公开 API。"""

from ysu_sdk.jwxt.client import JWXTClient
from ysu_sdk.jwxt.exceptions import (
    JWXTError,
    NotLoggedInError,
    JWXTProtocolError,
    JWXTBusinessError,
)
from ysu_sdk.jwxt.types import (
    AcademicCompletion,
    AcademicWarning,
    ClassPeriod,
    Course,
    CurrentWeek,
    EvaluationAnswer,
    EvaluationDetail,
    EvaluationTask,
    EvaluationType,
    Exam,
    GPAStats,
    Grade,
    GradeDistribution,
    GradeRanking,
    GradeStatistics,
    Question,
    QuestionOption,
    StudentInfo,
    TermCalendar,
    TrainingPlan,
)

__all__ = [
    "JWXTClient",
    "JWXTError",
    "NotLoggedInError",
    "JWXTProtocolError",
    "JWXTBusinessError",
    "AcademicCompletion",
    "AcademicWarning",
    "ClassPeriod",
    "Course",
    "CurrentWeek",
    "EvaluationAnswer",
    "EvaluationDetail",
    "EvaluationTask",
    "EvaluationType",
    "Exam",
    "GPAStats",
    "Grade",
    "GradeDistribution",
    "GradeRanking",
    "GradeStatistics",
    "Question",
    "QuestionOption",
    "StudentInfo",
    "TermCalendar",
    "TrainingPlan",
]
