"""教务系统子包公开 API。"""

from ysu_sdk.jwxt.client import JWXTClient
from ysu_sdk.jwxt.exceptions import (
    JWXTError,
    NotLoggedInError,
    JWXTProtocolError,
    JWXTBusinessError,
)
from ysu_sdk.jwxt.session import JWXTSession
from ysu_sdk.jwxt.types import (
    AcademicCompletion,
    AcademicCompletionGroup,
    AcademicWarning,
    ClassInfo,
    ClassPeriod,
    ClassroomInfo,
    CodeItem,
    Course,
    CourseAdjustment,
    CurrentWeek,
    EvaluationAnswer,
    EvaluationDetail,
    EvaluationTask,
    EvaluationType,
    Exam,
    GPAStats,
    Grade,
    GradeDistribution,
    GradeRanking,
    GradeStatistics,
    MakeupExamBatch,
    MakeupExamCourse,
    MajorInfo,
    OverallAdjustment,
    Question,
    QuestionOption,
    StudentInfo,
    TermCalendar,
    TrainingPlan,
    UnscheduledCourse,
)

__all__ = [
    "JWXTClient",
    "JWXTSession",
    "JWXTError",
    "NotLoggedInError",
    "JWXTProtocolError",
    "JWXTBusinessError",
    "AcademicCompletion",
    "AcademicCompletionGroup",
    "AcademicWarning",
    "ClassInfo",
    "ClassPeriod",
    "ClassroomInfo",
    "CodeItem",
    "Course",
    "CourseAdjustment",
    "CurrentWeek",
    "EvaluationAnswer",
    "EvaluationDetail",
    "EvaluationTask",
    "EvaluationType",
    "Exam",
    "GPAStats",
    "Grade",
    "GradeDistribution",
    "GradeRanking",
    "GradeStatistics",
    "MakeupExamBatch",
    "MakeupExamCourse",
    "MajorInfo",
    "OverallAdjustment",
    "Question",
    "QuestionOption",
    "StudentInfo",
    "TermCalendar",
    "TrainingPlan",
    "UnscheduledCourse",
]
